name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Grant execute permission for gradlew
      run: |
          cd server
          chmod 755 ./gradlew
    - name: Gradle run test
      run: |
        cd server
        chmod 
          ./gradlew test
      env:
        CI: true
  
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - name : Build Docker image
         env:
           IMAGE_TAG: ${{ github.sha }}
         run: |
            cd server
            cd chmod 755 ./Dockerfile
            docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
               
      
      
